root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  pre_cmd = ["pnpm --silent build"]
  cmd = "go build -o ./tmp/main ./src"
  bin = "./tmp/main"
  args_bin = []
  delay = 100
  exclude_dir = ["static", "assets", "tmp", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 8080
  enabled = true
  proxy_port = 3000

[screen]
  clear_on_rebuild = false
  keep_scroll = true
