# fly.toml app configuration file generated for filtrert on 2024-09-14T16:59:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'filtrert'
primary_region = 'arn'

[build]
  [build.args]
    GO_VERSION = '1.23.0'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
  source = 'data'
  destination = '/data'
